# TCL File Generated by Component Editor 13.0sp1
# Sat Aug 10 21:27:33 JST 2013
# DO NOT MODIFY


# 
# console_buf "Console Frame Buffer" v1.0
# @kimu_shu 2013.08.10.21:27:33
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module console_buf
# 
set_module_property DESCRIPTION ""
set_module_property NAME console_buf
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Memory
set_module_property AUTHOR @kimu_shu
set_module_property DISPLAY_NAME "Console Frame Buffer"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL console_buf
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file console_buf.vhd VHDL PATH console_buf.vhd TOP_LEVEL_FILE
add_fileset_file csbuf_color.qip OTHER PATH csbuf_color.qip
add_fileset_file csbuf_color.vhd VHDL PATH csbuf_color.vhd
add_fileset_file csbuf_font.qip OTHER PATH csbuf_font.qip
add_fileset_file csbuf_font.vhd VHDL PATH csbuf_font.vhd
add_fileset_file csbuf_hidx.qip OTHER PATH csbuf_hidx.qip
add_fileset_file csbuf_hidx.vhd VHDL PATH csbuf_hidx.vhd
add_fileset_file csbuf_text.qip OTHER PATH csbuf_text.qip
add_fileset_file csbuf_text.vhd VHDL PATH csbuf_text.vhd
add_fileset_file csbuf_vidx.qip OTHER PATH csbuf_vidx.qip
add_fileset_file csbuf_vidx.vhd VHDL PATH csbuf_vidx.vhd


# 
# parameters
# 
add_parameter PIXDEPTH INTEGER 16
set_parameter_property PIXDEPTH DEFAULT_VALUE 16
set_parameter_property PIXDEPTH DISPLAY_NAME PIXDEPTH
set_parameter_property PIXDEPTH TYPE INTEGER
set_parameter_property PIXDEPTH UNITS None
set_parameter_property PIXDEPTH HDL_PARAMETER true
add_parameter HW INTEGER 7
set_parameter_property HW DEFAULT_VALUE 7
set_parameter_property HW DISPLAY_NAME HW
set_parameter_property HW TYPE INTEGER
set_parameter_property HW UNITS None
set_parameter_property HW HDL_PARAMETER true
add_parameter VW INTEGER 6
set_parameter_property VW DEFAULT_VALUE 6
set_parameter_property VW DISPLAY_NAME VW
set_parameter_property VW TYPE INTEGER
set_parameter_property VW UNITS None
set_parameter_property VW HDL_PARAMETER true


# 
# display items
# 


# 
# connection point s1c
# 
add_interface s1c clock end
set_interface_property s1c clockRate 0
set_interface_property s1c ENABLED true
set_interface_property s1c EXPORT_OF ""
set_interface_property s1c PORT_NAME_MAP ""
set_interface_property s1c SVD_ADDRESS_GROUP ""

add_interface_port s1c csi_s1c_clk clk Input 1


# 
# connection point s1r
# 
add_interface s1r reset end
set_interface_property s1r associatedClock s1c
set_interface_property s1r synchronousEdges DEASSERT
set_interface_property s1r ENABLED true
set_interface_property s1r EXPORT_OF ""
set_interface_property s1r PORT_NAME_MAP ""
set_interface_property s1r SVD_ADDRESS_GROUP ""

add_interface_port s1r rsi_s1r_reset reset Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock s1c
set_interface_property s1 associatedReset s1r
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_address address Input 2
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point s2c
# 
add_interface s2c clock end
set_interface_property s2c clockRate 0
set_interface_property s2c ENABLED true
set_interface_property s2c EXPORT_OF ""
set_interface_property s2c PORT_NAME_MAP ""
set_interface_property s2c SVD_ADDRESS_GROUP ""

add_interface_port s2c csi_s2c_clk clk Input 1


# 
# connection point s2r
# 
add_interface s2r reset end
set_interface_property s2r associatedClock s1c
set_interface_property s2r synchronousEdges DEASSERT
set_interface_property s2r ENABLED true
set_interface_property s2r EXPORT_OF ""
set_interface_property s2r PORT_NAME_MAP ""
set_interface_property s2r SVD_ADDRESS_GROUP ""

add_interface_port s2r rsi_s2r_reset reset Input 1


# 
# connection point s2
# 
add_interface s2 avalon end
set_interface_property s2 addressUnits WORDS
set_interface_property s2 associatedClock s2c
set_interface_property s2 associatedReset s2r
set_interface_property s2 bitsPerSymbol 8
set_interface_property s2 burstOnBurstBoundariesOnly false
set_interface_property s2 burstcountUnits WORDS
set_interface_property s2 explicitAddressSpan 0
set_interface_property s2 holdTime 0
set_interface_property s2 linewrapBursts false
set_interface_property s2 maximumPendingReadTransactions 6
set_interface_property s2 readLatency 0
set_interface_property s2 readWaitStates 0
set_interface_property s2 readWaitTime 0
set_interface_property s2 setupTime 0
set_interface_property s2 timingUnits Cycles
set_interface_property s2 writeWaitTime 0
set_interface_property s2 ENABLED true
set_interface_property s2 EXPORT_OF ""
set_interface_property s2 PORT_NAME_MAP ""
set_interface_property s2 SVD_ADDRESS_GROUP ""

add_interface_port s2 avs_s2_address address Input 21
add_interface_port s2 avs_s2_read read Input 1
add_interface_port s2 avs_s2_readdata readdata Output pixdepth
add_interface_port s2 avs_s2_readdatavalid readdatavalid Output 1
set_interface_assignment s2 embeddedsw.configuration.isFlash 0
set_interface_assignment s2 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s2 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s2 embeddedsw.configuration.isPrintableDevice 0

