# TCL File Generated by Component Editor 13.1
# Tue Jul 29 00:35:46 JST 2014
# DO NOT MODIFY


# 
# rubic_r2n_converter "Rubic Rite to NiosII Instruction Converter" v1.0
# kimu_shu 2014.07.29.00:35:46
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module rubic_r2n_converter
# 
set_module_property DESCRIPTION ""
set_module_property NAME rubic_r2n_converter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR kimu_shu
set_module_property DISPLAY_NAME "Rubic Rite to NiosII Instruction Converter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL rubic_r2n_converter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file rubic_r2n_converter.vhd VHDL PATH rubic_r2n_converter.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file rubic_r2n_converter.vhd VHDL PATH rubic_r2n_converter.vhd


# 
# parameters
# 
add_parameter INST_ADDR_WIDTH INTEGER 26
set_parameter_property INST_ADDR_WIDTH DEFAULT_VALUE 26
set_parameter_property INST_ADDR_WIDTH DISPLAY_NAME INST_ADDR_WIDTH
set_parameter_property INST_ADDR_WIDTH TYPE INTEGER
set_parameter_property INST_ADDR_WIDTH UNITS None
set_parameter_property INST_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INST_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point rite
# 
add_interface rite avalon start
set_interface_property rite addressUnits WORDS
set_interface_property rite associatedClock clock
set_interface_property rite associatedReset reset
set_interface_property rite bitsPerSymbol 8
set_interface_property rite burstOnBurstBoundariesOnly false
set_interface_property rite burstcountUnits WORDS
set_interface_property rite doStreamReads false
set_interface_property rite doStreamWrites false
set_interface_property rite holdTime 0
set_interface_property rite linewrapBursts false
set_interface_property rite maximumPendingReadTransactions 0
set_interface_property rite readLatency 0
set_interface_property rite readWaitTime 1
set_interface_property rite setupTime 0
set_interface_property rite timingUnits Cycles
set_interface_property rite writeWaitTime 0
set_interface_property rite ENABLED true
set_interface_property rite EXPORT_OF ""
set_interface_property rite PORT_NAME_MAP ""
set_interface_property rite CMSIS_SVD_VARIABLES ""
set_interface_property rite SVD_ADDRESS_GROUP ""

add_interface_port rite r_address address Output 29
add_interface_port rite r_read read Output 1
add_interface_port rite r_readdata readdata Input 32
add_interface_port rite r_readdatavalid readdatavalid Input 1
add_interface_port rite r_waitrequest waitrequest Input 1


# 
# connection point nios2
# 
add_interface nios2 avalon end
set_interface_property nios2 addressUnits WORDS
set_interface_property nios2 associatedClock clock
set_interface_property nios2 associatedReset reset
set_interface_property nios2 bitsPerSymbol 8
set_interface_property nios2 burstOnBurstBoundariesOnly false
set_interface_property nios2 burstcountUnits WORDS
set_interface_property nios2 explicitAddressSpan 0
set_interface_property nios2 holdTime 0
set_interface_property nios2 isMemoryDevice true
set_interface_property nios2 linewrapBursts false
set_interface_property nios2 maximumPendingReadTransactions 7
set_interface_property nios2 readLatency 0
set_interface_property nios2 readWaitTime 1
set_interface_property nios2 setupTime 0
set_interface_property nios2 timingUnits Cycles
set_interface_property nios2 writeWaitTime 0
set_interface_property nios2 ENABLED true
set_interface_property nios2 EXPORT_OF ""
set_interface_property nios2 PORT_NAME_MAP ""
set_interface_property nios2 CMSIS_SVD_VARIABLES ""
set_interface_property nios2 SVD_ADDRESS_GROUP ""

add_interface_port nios2 n_address address Input "(inst_addr_width) - (4) + 1"
add_interface_port nios2 n_read read Input 1
add_interface_port nios2 n_readdata readdata Output 128
add_interface_port nios2 n_readdatavalid readdatavalid Output 1
add_interface_port nios2 n_waitrequest waitrequest Output 1
set_interface_assignment nios2 embeddedsw.configuration.isFlash 0
set_interface_assignment nios2 embeddedsw.configuration.isMemoryDevice 1
set_interface_assignment nios2 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment nios2 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ctrl
# 
add_interface ctrl avalon end
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock clock
set_interface_property ctrl associatedReset reset
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitTime 1
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0
set_interface_property ctrl ENABLED true
set_interface_property ctrl EXPORT_OF ""
set_interface_property ctrl PORT_NAME_MAP ""
set_interface_property ctrl CMSIS_SVD_VARIABLES ""
set_interface_property ctrl SVD_ADDRESS_GROUP ""

add_interface_port ctrl c_address address Input 7
add_interface_port ctrl c_write write Input 1
add_interface_port ctrl c_writedata writedata Input 32
add_interface_port ctrl c_read read Input 1
add_interface_port ctrl c_readdata readdata Output 32
set_interface_assignment ctrl embeddedsw.configuration.isFlash 0
set_interface_assignment ctrl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ctrl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ctrl embeddedsw.configuration.isPrintableDevice 0

