# TCL File Generated by Component Editor 9.1sp2
# Sun Aug 21 00:50:11 JST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | avalonif_spu "avalonif_spu" v1.0
# | null 2011.08.21.00:50:11
# | 
# | 
# | D:/PROJECT/DE0/cineraria_LMi/loreley/avalonif_spu.vhd
# | 
# |    ./avalonif_spu.vhd syn, sim
# |    ./loreley_businterface.vhd syn, sim
# |    ./loreley_cacheram.vhd syn, sim
# |    ./loreley_core.vhd syn, sim
# |    ./loreley_dacif_bu9480f_ds.vhd syn, sim
# |    ./loreley_decoder.vhd syn, sim
# |    ./loreley_dpram.vhd syn, sim
# |    ./loreley_envram.mif 
# |    ./loreley_envram.vhd syn, sim
# |    ./loreley_irqencode.vhd syn, sim
# |    ./loreley_lfsr.vhd syn, sim
# |    ./loreley_slotengine.vhd syn, sim
# |    ./loreley_waveadder.vhd syn, sim
# |    ./loreley_wromcache.vhd syn, sim
# |    ./multiple_16x16.vhd syn, sim
# |    ./multiple_16x9.vhd syn, sim
# |    ./STARROSE_SPU.vhd syn, sim
# |    ./wavebuffer.vhd syn, sim
# |    ./wsg_dsdac8.vhd syn, sim
# |    ./wsg_spdif.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module avalonif_spu
# | 
set_module_property NAME avalonif_spu
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP Peripherals
set_module_property DISPLAY_NAME avalonif_spu
set_module_property TOP_LEVEL_HDL_FILE avalonif_spu.vhd
set_module_property TOP_LEVEL_HDL_MODULE avalonif_spu
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file avalonif_spu.vhd {SYNTHESIS SIMULATION}
add_file loreley_businterface.vhd {SYNTHESIS SIMULATION}
add_file loreley_cacheram.vhd {SYNTHESIS SIMULATION}
add_file loreley_core.vhd {SYNTHESIS SIMULATION}
add_file loreley_dacif_bu9480f_ds.vhd {SYNTHESIS SIMULATION}
add_file loreley_decoder.vhd {SYNTHESIS SIMULATION}
add_file loreley_dpram.vhd {SYNTHESIS SIMULATION}
add_file loreley_envram.mif ""
add_file loreley_envram.vhd {SYNTHESIS SIMULATION}
add_file loreley_irqencode.vhd {SYNTHESIS SIMULATION}
add_file loreley_lfsr.vhd {SYNTHESIS SIMULATION}
add_file loreley_slotengine.vhd {SYNTHESIS SIMULATION}
add_file loreley_waveadder.vhd {SYNTHESIS SIMULATION}
add_file loreley_wromcache.vhd {SYNTHESIS SIMULATION}
add_file multiple_16x16.vhd {SYNTHESIS SIMULATION}
add_file multiple_16x9.vhd {SYNTHESIS SIMULATION}
add_file STARROSE_SPU.vhd {SYNTHESIS SIMULATION}
add_file wavebuffer.vhd {SYNTHESIS SIMULATION}
add_file wsg_dsdac8.vhd {SYNTHESIS SIMULATION}
add_file wsg_spdif.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point global
# | 
add_interface global clock end

set_interface_property global ENABLED true

add_interface_port global csi_global_reset reset Input 1
add_interface_port global csi_global_clock clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point m1_clock
# | 
add_interface m1_clock clock end

set_interface_property m1_clock ENABLED true

add_interface_port m1_clock csi_m1_clock clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point m1
# | 
add_interface m1 avalon start
set_interface_property m1 associatedClock m1_clock
set_interface_property m1 burstOnBurstBoundariesOnly true
set_interface_property m1 doStreamReads false
set_interface_property m1 doStreamWrites false
set_interface_property m1 linewrapBursts false

set_interface_property m1 ASSOCIATED_CLOCK m1_clock
set_interface_property m1 ENABLED true

add_interface_port m1 avm_m1_address address Output 25
add_interface_port m1 avm_m1_burstcount burstcount Output 3
add_interface_port m1 avm_m1_read read Output 1
add_interface_port m1 avm_m1_readdata readdata Input 16
add_interface_port m1 avm_m1_readdatavalid readdatavalid Input 1
add_interface_port m1 avm_m1_waitrequest waitrequest Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 associatedClock global
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ASSOCIATED_CLOCK global
set_interface_property s1 ENABLED true

add_interface_port s1 avs_s1_address address Input 9
add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_byteenable byteenable Input 4
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point irq_s1
# | 
add_interface irq_s1 interrupt end
set_interface_property irq_s1 associatedAddressablePoint s1

set_interface_property irq_s1 ASSOCIATED_CLOCK global
set_interface_property irq_s1 ENABLED true

add_interface_port irq_s1 avs_s1_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK global
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end clk_128fs export Input 1
add_interface_port conduit_end DAC_BCLK export Output 1
add_interface_port conduit_end DAC_LRCK export Output 1
add_interface_port conduit_end DAC_DATA export Output 1
add_interface_port conduit_end AUD_L export Output 1
add_interface_port conduit_end AUD_R export Output 1
add_interface_port conduit_end SPDIF export Output 1
# | 
# +-----------------------------------
